config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'my_room/index'
    get 'access_room/index'
    get 'access_room/:id/access', to: 'access_room#access'
    post '/room_verify/:id', to: 'access_room#room_verify', as: 'room_verify'
    get 'welcome/index'
    get 'search', to: 'search#questions'
    resources :my_room
  end
  namespace :admins_backoffice do
    get 'welcome/index' # Dashboard
    get 'search', to: 'search#questions'
    get  '/rooms/activities_list', to: 'rooms#activities_list'
    get  '/rooms/:room_id/activity_new', to: 'rooms#activity_new'

    resources :admins #Admins
    resources :subjects #Assuntos
    resources :questions #Perguntas
    resources :rooms #Salas Virtuais
    resources :activities #atividades
  end
  devise_for :users
  devise_for :admins

  root to: 'site/welcome#index'
  get 'inicio', to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  paginates_per 10

  has_many :archives, dependent: :destroy
  accepts_nested_attributes_for :archives, allow_destroy: true
  
  belongs_to :room, inverse_of: :activitys
  belongs_to :admin
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,:recoverable,
         :rememberable, :validatable

  has_many :rooms
  #kaminari 
  paginates_per 9
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, inverse_of: :answers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader

  belongs_to :activity, inverse_of: :archives
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
end

app/models/room.rb
class Room < ApplicationRecord
    
    has_many :activitys, dependent: :destroy
    accepts_nested_attributes_for :activitys, reject_if: :all_blank, allow_destroy: true
    belongs_to :admin, inverse_of: :rooms

    has_many :room_users
    has_many :users, through: :room_users
    
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
    paginates_per 10
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout '/admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout :layout_by_resource

    
    protected

    def layout_by_resource
        if devise_controller? && resource_class == Admin
            "admin_devise"
        elsif devise_controller? && resource_class == User
            "user_devise"
        else
            "application"
        end
    end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/controllers/users_backoffice/access_room_controller.rb
class UsersBackoffice::AccessRoomController < UsersBackofficeController
    before_action :set_room, only: %i[room_verify access]
    def index
        @rooms = Room.includes(:admin).page(params[:page]).per(3)
    end
    
    def access
    end
    def room_verify
        if @room.code == params[:code]
            RoomUser.create!(user_id: current_user.id, room_id: @room.id)
            redirect_to users_backoffice_access_room_index_path, notice:"Bem vindo #{current_user.email}"
        else
            render :access, notice:'Código invalido, consulte seu professor'
        end
    end
    
    

    private

    def params_room_user
        params.require(:room_user).permit(:room_id, :user_id)
    end

    def params_room
        params.require(:room).permit(:code)
    end

    def set_room
        @room = Room.find(params[:id])
    end
end

app/controllers/users_backoffice/my_room_controller.rb
class UsersBackoffice::MyRoomController < UsersBackofficeController
  before_action :set_my_room, only: %i[destroy]

  def index
    @my_rooms = Room.joins(:room_users).where(room_users: { user_id: current_user.id }).page(params[:page]).per(5)
  end

  def destroy
    if @room_user.destroy
        redirect_to admins_backoffice_rooms_path, notice: "Desconectado com sucesso!"
    else
        render :index
    end
  end

  private

  def set_my_room
    @room_user = RoomUser.find(params[:id])
  end
  
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/helpers/admins_backoffice/rooms_helper.rb
module AdminsBackoffice::RoomsHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object = nil, method = nil)
        if object and method
            object.model.human_attribute_name(method)
        else
            "informe os parâmetros corretamente!"
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_backoffice/welcome_helper.rb
module SiteBackoffice::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/access_room_helper.rb
module UsersBackoffice::AccessRoomHelper
end

app/helpers/users_backoffice/my_room_helper.rb
module UsersBackoffice::MyRoomHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/users_backoffice/access_room/access.html.erb
<div class="container">
  <div class="card">
  </div>  
  <div class="card">
    <div class="card-header" style="margin:auto;">
      <%#= image_tag "#{room.attachment}", class:'img-fluid', style:'width: 1000px; height: 600px; border: none;' %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @room.room_name %></h5>
      <h5 class="card-title"><%= @room.description %></h5>
      <table>
        <thead>
            <tr role="row">
                <th>Nome do Professor: <%= @room.admin.description %></th>
            </tr>
        </thead>
        <tbody>
          <td>
          <div style="line-height: 50px;">
            <%= form_with(url: users_backoffice_room_verify_path(@room.id), local: true, method: :post) do |form| %>
                <p id="notice"><%= notice %></p>
                <div class="form-floating mb-3">
                    <%= form.label :code, 'Código da sala' %>
                    <%= form.text_field :code, class:"form-control", placeholder:"Insira o código" %> 
                </div>
                <button class="btn btn-primary" type="submit">Enviar</button>
            <% end %>
          </div>  
          </td>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users_backoffice/access_room/index.html.erb
<div class="container">
  <div class="card">
  <p id="notice"><%= notice %></p>
  </div>  
  <% @rooms.each do |room| %>
  <div class="card">
    <div class="card-header" style="margin:auto;">
      <%#= image_tag "#{room.attachment}", class:'img-fluid', style:'width: 1000px; height: 600px; border: none;' %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= room.room_name %></h5>
      <h5 class="card-title"><%= room.description %></h5>
      <h5 class="card-title"><%= room.code %></h5>
      <table>
        <thead>
            <tr role="row">
                <th>Nome do Professor: <%= room.admin.description %></th>
            </tr>
        </thead>
        <tbody>
          <td>
          <div style="line-height: 50px;">
            <%= link_to users_backoffice_path(room), class: "btn btn-success" do %>
                <i class="fa fa-bars"></i> Acessar 
            <% end %>
            </div>  
          </td>
        </tbody>
      </table>
    </div>
  </div>
  <% end %>
</div>
<%= paginate @rooms %>

app/views/users_backoffice/my_room/index.html.erb
<div class="container">
  <div class="card">
  </div>  
  <% @my_rooms.each do |room| %>
  <div class="card">
    <div class="card-header" style="margin:auto;">
      <%#= image_tag "#{room.attachment}", class:'img-fluid', style:'width: 1000px; height: 600px; border: none;' %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= room.room_name %></h5>
      <h5 class="card-title"><%= room.description %></h5>
      <table>
        <thead>
            <tr role="row">
                <th>Nome do Professor: <%= room.admin.description %></th>
            </tr>
        </thead>
        <tbody>
          <td>
            <div style="line-height: 50px;">
            <%= link_to '', class: "btn btn-danger" do %>
                <i class=""></i> 
            <% end %>
            </div>  
          </td>
        </tbody>
      </table>
    </div>
  </div>
  <% end %>
</div>
<%= paginate @my_rooms %>