config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'my_room/index'
    get 'access_room/index'
    get 'access_room/:id/access', to: 'access_room#access'
    post '/room_verify/:id', to: 'access_room#room_verify', as: 'room_verify'
    get 'welcome/index'
    get 'search', to: 'search#questions'
    resources :my_room
  end
  namespace :admins_backoffice do
    get 'welcome/index' # Dashboard
    get 'search', to: 'search#questions'
    get  '/rooms/activities_list', to: 'rooms#activities_list'
    get  '/rooms/:room_id/activity_new', to: 'rooms#activity_new'

    resources :admins #Admins
    resources :subjects #Assuntos
    resources :questions #Perguntas
    resources :rooms #Salas Virtuais
    resources :activities #atividades
  end
  devise_for :users
  devise_for :admins

  root to: 'site/welcome#index'
  get 'inicio', to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
    paginates_per 10
end

app/controllers/admins_backoffice/activities_controller.rb
class AdminsBackoffice::ActivitiesController < AdminsBackofficeController
  before_action :set_activity, only: %i[edit update destroy]
  
  def index
    @activities = Activity.where(admin_id: current_admin.id).page(params[:page]).per(5)
  end

  def edit
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to admins_backoffice_room_path(@activity.room_id), notice: 'Atividade criada com sucesso!'
    else
      render :new
    end
  end

  def update
    if @activity.update(activity_params)
        redirect_to admins_backoffice_room_path(@activity.room_id), notice: "Atividade atualizada com sucesso!"
    else
        render :edit
    end
  end


  def destroy
    if @activity.destroy
        redirect_to admins_backoffice_room_path(@activity.room_id), notice: "Sala virtual excluída com sucesso!"
    else
        render :index
    end
  end
  
  private
  
  def activity_params
    params.require(:activity).permit(:activity_name, :description, :start_time, :end_time, :points, :admin_id,
                                     :room_id, archives_attributes: [:id, :description, :attachment, :_destroy])
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end
  
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :password_verify, only:[:update]
  before_action :set_admin, only:[:edit, :update, :destroy]

  def index
    @admins = Admin.all.page(params[:page])
  end

  def new
    @admin = Admin.new
  end
  
  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Administrador criado com sucesso."
    else
      render :new 
    end
  end
  

  def edit
  end

  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado com sucesso."
    else
      render :edit 
    end
  end
  
  def destroy
    if  @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Administrador Excluido com sucesso!"
    else
      render :index
    end
  end
  
  private

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
  
  def password_verify
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank? 
      params[:admin].extract!(:password, :password_confirmation) 
    end
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end
  
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController <AdminsBackofficeController
    before_action :set_question, only: [:edit, :update, :destroy]
    before_action :get_subjects, only: [:edit, :new]

     def index
        @questions = Question.includes(:subject)
                             .order(:description)
                             .page(params[:page])
     end

     def new
        @question = Question.new
     end

     def create
        @question = Question.new(params_question)
        if @question.save
            redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
        else
            render :new
        end
     end

     def edit
     end

     def update
        if @question.update(params_question)
            redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso!"
        else
            render :edit
        end
     end

     def destroy
        if @question.destroy
            redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
        else
            render :index
        end
     end

     private

     def params_question
        params.require(:question).permit(:description, :subject_id,
                                         answers_attributes: 
                                         [:id, :description, :correct, :_destroy])
     end

     def set_question
         @question = Question.find(params[:id])
     end

     def get_subjects
         @subjects = Subject.all
     end
     
end

app/controllers/admins_backoffice/rooms_controller.rb
class AdminsBackoffice::RoomsController < AdminsBackofficeController
    before_action :set_room, only: %i[edit update destroy show]
    before_action :set_activity, only: %i[activity_edit activity_update activity_destroy]
  
    def index
      @rooms = Room.includes(:admin).page(params[:page]).per(3)
    end

    def new
        @room = Room.new
    end

    def show
        @activities = Activity.where(admin_id: current_admin.id).page(params[:page]).per(5)
    end

    def create
        @room = Room.new(params_room)
        if @room.save
            redirect_to admins_backoffice_rooms_path, notice: "Sala virtual cadastrada com sucesso!"
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @room.update(params_room)
            redirect_to admins_backoffice_rooms_path, notice: "Sala virtual atualizada com sucesso!"
        else
            render :edit
        end
    end

    def destroy
        if @room.destroy
            redirect_to admins_backoffice_rooms_path, notice: "Sala virtual excluída com sucesso!"
        else
            render :index
        end
    end

    def activities_list
        @rooms = Room.all
    end
    
    def activity_edit
    end
  
    def activity_new
      @activity = Activity.new
    end

    private

    def activity_params
        params.require(:activity).permit(:activity_name, :image, :description, :start_time, :end_time,
                                         :points, :admin_id, :room_id, archives_attributes: [:id, :description, :attachment, :_destroy])
    end
    
    def set_activity
        @activity = Activity.find(params[:id])
    end

    def params_room
        params.require(:room).permit(:room_name, :description, :code, :password, :admin_id)
    end

    def set_room
        @room = Room.find(params[:id])
    end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
    before_action :set_subject, only:[:edit, :update, :destroy]
  
    def index
      @subjects = Subject.all.order(:description).page(params[:page])
    end
  
    def new
      @subject = Subject.new
    end
    
    def create
      @subject = Subject.new(params_subject)
      if params[:subject][:description].blank?
        render :new 
      else
        @subject.save
        redirect_to admins_backoffice_subjects_path, notice: "Assunto criado com sucesso."
      end
    end
    
  
    def edit
    end
  
    def update
      if @subject.update(params_subject)
        redirect_to admins_backoffice_subjects_path, notice: "Assunto atualizado com sucesso."
      else
        render :edit 
      end
    end
    
    def destroy
      if  @subject.destroy
        redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área excluído com sucesso!"
      else
        render :index
      end
    end
  
    
    private

    def params_subject
      params.require(:subject).permit(:description)
    end    

    def set_subject
      @subject = Subject.find(params[:id])
    end
    
  end
  

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @questions = Question.includes(:subject)
                          .order(:description)
                          .page(params[:page])
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout '/admins_backoffice'
end

app/helpers/admins_backoffice/activities_helper.rb
module AdminsBackoffice::ActivitiesHelper
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/rooms_helper.rb
module AdminsBackoffice::RoomsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object = nil, method = nil)
        if object and method
            object.model.human_attribute_name(method)
        else
            "informe os parâmetros corretamente!"
        end
    end
    
end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: {action_message: t('messages.editing', model: @subject.model_name.human)} %>

app/views/admins_backoffice/subjects/index.html.erb
<h1><%= t('messages.listing', model: @subjects.model_name.human(count: 2)) %></h1>

<div class="card shadow mb-4">
<div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Lista</h6>
</div>
<div class="card-body">
<div class="table-responsive">
    <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4"><div class="row"><div class="col-sm-12 col-md-6"><div class="dataTables_length" id="dataTable_length"><label>Mostrar<select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select></label></div></div><div class="col-sm-12 col-md-6"><div id="dataTable_filter" class="dataTables_filter"><label>Procurar:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label></div></div></div><div class="row"><div class="col-sm-12">
    <table class="table table-bordered dataTable" id="dataTable" width="50%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
        <thead>
            <tr role="row">
            <th>ID</th>
            <th><%= translate_attribute(@subjects, :description) %></th>
            <th>
                <%= link_to new_admins_backoffice_subject_path, class: "btn btn-success btn-circle" do %>
                    <i class="fa fa-plus"></i>
                <% end %>
            </th>
            </tr>
        </thead>
        <tbody>
            <% @subjects.each do |subject| %>    
            <tr>
                <th><%= subject.id %></th>
                <th><%= subject.description %></th>
                <th style="width: 110px;">
                    <%= link_to edit_admins_backoffice_subject_path(subject), class: "btn btn-primary btn-circle" do %>
                        <i class="fa fa-edit"></i>
                    <% end %>
                    <%= link_to admins_backoffice_subject_path(subject), method: :delete, class: "btn btn-danger btn-circle", data: { confirm: t('messages.confirm_with', item: subject.description.truncate(15))} do %>
                        <i class="fas fa-trash"></i>
                    <% end %>  
                </th>
            </tr> 
            <% end %>
        </tbody>
        </table>
        <div class="text-center">
            <%= paginate @subjects %>
        </div>
    </div>
</div>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: {action_message: t('messages.creating', model: @subject.model_name.human)} %>